# Generated by Django 3.1.4 on 2020-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='MyBlog', max_length=255),
        ),
    ]
